### ISSUE TITLE
Inactive notice

### ISSUE THREAD

**Issue by akshaybabloo** [akshaybabloo/release-exporter#56]
This project will soon be inactive. I am working on a new project that does this and more.

**Comment by truh** [comment]
Hello @akshaybabloo. Thank you for your work and for releasing the release-exporter.

Is the project already inactive?

Have you already realized your new project?

If I wish to improve release-exporter, should I fork it or should I open PR with my improvements.

**Comment by akshaybabloo** [comment]
Hi. Thank you for using this project.

I haven't been able to finish the other one yet, not sure if I can.

You can absolutely fork it and put in your PR.
